CREATE TABLE IF NOT EXISTS Journeys (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, start INTEGER, end INTEGER)

CREATE TABLE IF NOT EXISTS Tracks (id INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY(journey_id) REFERENCES Journeys(id), timestamp INTEGER)

CREATE TABLE IF NOT EXISTS Photos (id INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY(journey_id) REFERENCES Journeys(id), latitude REAL, longitude REAL, timestamp INTEGER, uri TEXT)